### ISSUE TITLE
Add sbitems metadata to scripts

### ISSUE THREAD

**Issue by ailin-nemui** [mh-source/irssi-scripts#1]
```
sbitems => 'mh_sbuserinfo',
sbitems => 'mh_sbmore',
sbitems => 'mh_sbsplitmode', 
```
will give scriptassist users a helpful hint

**Comment by mh-source** [comment]
Thanks for the suggestion, I appreciate being poked if there are any issues with my scripts.

I do not know how to open multiple pull requests for different scripts at the same time for irssi.org, so i will update them as you accept them :-)  (at least for those that are on irssi.org)

**Comment by ailin-nemui** [comment]
you would have to `git checkout -b newbranch` for each of them

**Comment by mh-source** [comment]
(note to self: when hold_mode is accepted submit the last sbsplitmode and we are done here)

**Comment by mh-source** [comment]
(sbslitmode submitted, close this when accepted)

**Comment by mh-source** [comment]
(all done)
